### ISSUE TITLE
font changing ?!

### ISSUE THREAD

**Issue by sixpak** [phil65/screensaver.qlock#6]
moinmoin ...
... da als Wohnort "Cologne" angegeben ist, versuche ich es mal auf "germanisch" ;)

Momentan kann man die Schriftart und -farbe ja nur in der Datei script-python-qlock.xml anpassen.
Ist irgendwann geplant, noch eine Art "theming" in die AddOn Config einzubinden?

greetz

Der Rico

**Comment by phil65** [comment]
nee, nicht geplant.  Am liebsten würde ich dieses add-on nicht mal maintainen. Werde nicht mehr als nötig machen. ;)
